extends: stylelint-config-standard

rules:
  block-closing-brace-newline-before: always
  block-no-single-line: true
  block-opening-brace-newline-after: always
  declaration-block-properties-order: alphabetical
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-colon-space-after: always-single-line
  declaration-no-important: true
  font-family-name-quotes: always-unless-keyword
  function-comma-space-after: always
  function-parentheses-space-inside: never
  function-url-quotes: always
  no-duplicate-selectors: true
  property-no-unknown: true
  property-no-vendor-prefix: true
  selector-no-id: true
  string-quotes: double
  value-keyword-case: lower

